export interface IshiharaPlate {
  id: number;
  imageUrl: string;
  question: string;
  options: string[];
  normalAnswer: string;
  protanAnswer?: string;
  deutanAnswer?: string;
  type?: "screening" | "protan" | "deutan" | "demo";
}

export const PLATES: IshiharaPlate[] = [
  {
    id: 1,
    imageUrl: "ishihara/Plate_01.png",
    question: "What number do you see?",
    options: ["12", "17", "Nothing", "21"],
    normalAnswer: "12",
  },
  {
    id: 2,
    imageUrl: "ishihara/Plate_02.png",
    question: "What number do you see?",
    options: ["8", "3", "Nothing", "6"],
    normalAnswer: "8",
  },
  {
    id: 3,
    imageUrl: "ishihara/Plate_03.png",
    question: "What number do you see?",
    options: ["6", "5", "Nothing", "9"],
    normalAnswer: "6",
  },
  {
    id: 4,
    imageUrl: "ishihara/Plate_04.png",
    question: "What number do you see?",
    options: ["29", "70", "Nothing", "26"],
    normalAnswer: "29",
  },
  {
    id: 5,
    imageUrl: "ishihara/Plate_05.png",
    question: "What number do you see?",
    options: ["57", "35", "Nothing", "53"],
    normalAnswer: "57",
  },
  {
    id: 6,
    imageUrl: "ishihara/Plate_06.png",
    question: "What number do you see?",
    options: ["5", "2", "Nothing", "3"],
    normalAnswer: "5",
  },
  {
    id: 7,
    imageUrl: "ishihara/Plate_07.png",
    question: "What number do you see?",
    options: ["3", "5", "Nothing", "8"],
    normalAnswer: "3",
  },
  {
    id: 8,
    imageUrl: "ishihara/Plate_08.png",
    question: "What number do you see?",
    options: ["15", "17", "Nothing", "13"],
    normalAnswer: "15",
  },
  {
    id: 9,
    imageUrl: "ishihara/Plate_09.png",
    question: "What number do you see?",
    options: ["74", "21", "Nothing", "71"],
    normalAnswer: "74",
  },
  {
    id: 10,
    imageUrl: "ishihara/Plate_10.png",
    question: "What number do you see?",
    options: ["2", "Nothing", "8", "6"],
    normalAnswer: "2",
  },
  {
    id: 11,
    imageUrl: "ishihara/Plate_11.png",
    question: "What number do you see?",
    options: ["6", "Nothing", "2", "8"],
    normalAnswer: "6",
  },
  {
    id: 12,
    imageUrl: "ishihara/Plate_12.png",
    question: "What number do you see?",
    options: ["97", "Nothing", "87", "91"],
    normalAnswer: "97",
  },
  {
    id: 13,
    imageUrl: "ishihara/Plate_13.png",
    question: "What number do you see?",
    options: ["45", "Nothing", "43", "15"],
    normalAnswer: "45",
  },
  {
    id: 14,
    imageUrl: "ishihara/Plate_14.png",
    question: "What number do you see?",
    options: ["5", "Nothing", "3", "8"],
    normalAnswer: "5",
  },
  {
    id: 15,
    imageUrl: "ishihara/Plate_15.png",
    question: "What number do you see?",
    options: ["7", "Nothing", "1", "4"],
    normalAnswer: "7",
  },
  {
    id: 16,
    imageUrl: "ishihara/Plate_16.png",
    question: "What number do you see?",
    options: ["16", "Nothing", "18", "10"],
    normalAnswer: "16",
  },
  {
    id: 17,
    imageUrl: "ishihara/Plate_17.png",
    question: "What number do you see?",
    options: ["73", "Nothing", "78", "13"],
    normalAnswer: "73",
  },
  {
    id: 18,
    imageUrl: "ishihara/Plate_18.png",
    question: "What number do you see?",
    options: ["Nothing", "5", "3", "8"],
    normalAnswer: "Nothing",
  },
  {
    id: 19,
    imageUrl: "ishihara/Plate_19.png",
    question: "What number do you see?",
    options: ["Nothing", "2", "7", "4"],
    normalAnswer: "Nothing",
  },
  {
    id: 20,
    imageUrl: "ishihara/Plate_20.png",
    question: "What number do you see?",
    options: ["Nothing", "45", "43", "15"],
    normalAnswer: "Nothing",
  },
  {
    id: 21,
    imageUrl: "ishihara/Plate_21.png",
    question: "What number do you see?",
    options: ["Nothing", "73", "13", "78"],
    normalAnswer: "Nothing",
  },
  {
    id: 22,
    imageUrl: "ishihara/Plate_22.png",
    question: "What number do you see?",
    options: ["26", "6", "2", "Nothing"],
    normalAnswer: "26",
    protanAnswer: "6",
    deutanAnswer: "2",
  },
  {
    id: 23,
    imageUrl: "ishihara/Plate_23.png",
    question: "What number do you see?",
    options: ["42", "2", "4", "Nothing"],
    normalAnswer: "42",
    protanAnswer: "2",
    deutanAnswer: "4",
  },
  {
    id: 24,
    imageUrl: "ishihara/Plate_24.png",
    question: "What number do you see?",
    options: ["35", "5", "3", "Nothing"],
    normalAnswer: "35",
    protanAnswer: "5",
    deutanAnswer: "3",
  },
  {
    id: 25,
    imageUrl: "ishihara/Plate_25.png",
    question: "What number do you see?",
    options: ["96", "6", "9", "Nothing"],
    normalAnswer: "96",
    protanAnswer: "6",
    deutanAnswer: "9",
  },
  {
    id: 26,
    imageUrl: "ishihara/Plate_26.png",
    question: "What line(s) do you see?",
    options: [
      "Purple and red line",
      "Only purple line",
      "Only red line",
      "Nothing",
    ],
    normalAnswer: "Purple and red line",
    protanAnswer: "Only purple line",
    deutanAnswer: "Only red line",
  },
  {
    id: 27,
    imageUrl: "ishihara/Plate_27.png",
    question: "What line(s) do you see?",
    options: [
      "Purple and red line",
      "Only purple line",
      "Only red line",
      "Nothing",
    ],
    normalAnswer: "Purple and red line",
    protanAnswer: "Only purple line",
    deutanAnswer: "Only red line",
  },
  {
    id: 28,
    imageUrl: "ishihara/Plate_28.png",
    question: "What line(s) do you see?",
    options: ["Nothing", "A line", "Two lines", "A curve"],
    normalAnswer: "Nothing",
  },
  {
    id: 29,
    imageUrl: "ishihara/Plate_29.png",
    question: "What line(s) do you see?",
    options: ["Nothing", "A line", "Two lines", "A curve"],
    normalAnswer: "Nothing",
  },
  {
    id: 30,
    imageUrl: "ishihara/Plate_30.png",
    question: "What line(s) do you see?",
    options: ["Blue-green line", "Nothing", "Orange line", "Red line"],
    normalAnswer: "Blue-green line",
  },
  {
    id: 31,
    imageUrl: "ishihara/Plate_31.png",
    question: "What line(s) do you see?",
    options: ["Blue-green line", "Nothing", "Orange line", "Red line"],
    normalAnswer: "Blue-green line",
  },
  {
    id: 32,
    imageUrl: "ishihara/Plate_32.png",
    question: "What line(s) do you see?",
    options: ["Orange line", "Nothing", "Blue-green line", "A false line"],
    normalAnswer: "Orange line",
  },
  {
    id: 33,
    imageUrl: "ishihara/Plate_33.png",
    question: "What line(s) do you see?",
    options: ["Orange line", "Nothing", "Blue-green line", "A false line"],
    normalAnswer: "Orange line",
  },
  {
    id: 34,
    imageUrl: "ishihara/Plate_34.png",
    question: "What line(s) do you see?",
    options: [
      "Blue-green and yellow-green line",
      "Red-green and violet line",
      "Nothing",
      "Only violet line",
    ],
    normalAnswer: "Blue-green and yellow-green line",
  },
  {
    id: 35,
    imageUrl: "ishihara/Plate_35.png",
    question: "What line(s) do you see?",
    options: [
      "Blue-green and yellow-green line",
      "Blue-green and violet line",
      "Nothing",
      "Only violet line",
    ],
    normalAnswer: "Blue-green and yellow-green line",
  },
  {
    id: 36,
    imageUrl: "ishihara/Plate_36.png",
    question: "What line(s) do you see?",
    options: [
      "Violet and orange line",
      "Blue-green and violet line",
      "Nothing",
      "Only orange line",
    ],
    normalAnswer: "Violet and orange line",
  },
  {
    id: 37,
    imageUrl: "ishihara/Plate_37.png",
    question: "What line(s) do you see?",
    options: [
      "Violet and orange line",
      "Blue-green and violet line",
      "Nothing",
      "Only orange line",
    ],
    normalAnswer: "Violet and orange line",
  },
  {
    id: 38,
    imageUrl: "ishihara/Plate_38.png",
    question: "What line(s) do you see?",
    options: ["A line", "Nothing", "Two lines", "A curve"],
    normalAnswer: "A line",
  },
];
